"""Integration tests for the PDF text extractor (litexplorer.services.pdf).

These tests run against committed synthetic fixtures in tests/fixtures/pdfs/.
The fixtures were generated by tests/fixtures/generate_fixtures.py (fpdf2 +
matplotlib) and contain only public-domain lorem ipsum text — no copyrighted
material.

=== Expected extraction order for two_column.pdf ===

The page has a genuine two-column body layout:

  Full-width zone (left group, sorted by top)
  ──────────────────────────────────────────
  Title:    "Synthetic Test"   x0 < mid_x ≈ 298 pt  (y ≈ 46 pt)
            "Paper"            x0 ≥ mid_x             → RIGHT group
  Authors:  "Alice Example,"   x0 < mid_x             → LEFT group
            "Bob Example"      x0 ≥ mid_x             → RIGHT group
  Abstract: most words         x0 < mid_x             → LEFT group
            scattered words    x0 ≥ mid_x             → RIGHT group

  LEFT group (x0 < mid_x, sorted by top)
  ───────────────────────────────────────
  "Synthetic Test" (title fragment, y ≈ 46)
  "Alice Example," (author fragment, y ≈ 68)
  Abstract words in left half (y ≈ 93–200)
  LEFTCOL body: … ALPHA … BETA … GAMMA … (y ≈ 200–450)
  Caption words in left half: "Figure 1: A" (y ≈ 470)

  RIGHT group (x0 ≥ mid_x, sorted by top)
  ────────────────────────────────────────
  "Paper" (title fragment, y ≈ 46)
  "Bob Example" (author fragment, y ≈ 68)
  Abstract words in right half (y ≈ 93–200)
  RIGHTCOL body: … DELTA … EPSILON … ZETA … (y ≈ 200–450)
  Caption words in right half: "sine wave." (y ≈ 470)

  Final output: [LEFT group text] \\n\\n [RIGHT group text]

_detect_two_column returns True because the right column's left margin
(x0 ≈ 312 pt) concentrates many line-starts in the [310-319] bin
(ratio ≈ 3.3× the page-wide average), triggering heuristic 2.

Unambiguous guarantees:
  • "LEFTCOL" appears before "RIGHTCOL"   (different column groups)
  • "Synthetic" is in the left group      (uniquely identifies title)
  • "ABSTRACT:" is in the left group      (full-width but starts left)
  • "Figure 1" is in the left group       (first three caption words)

Note: "Synthetic Test Paper" is NOT a contiguous substring — "Paper"
starts at x0 ≈ 332 pt (≥ mid_x) and falls into the right group.

=== Expected extraction order for single_column.pdf ===

All body text occupies the full page width (42–553 pt).  Word x0 values
are spread uniformly; no bin near mid_x is empty and no spike ≥ 2.5×
average appears in the right half.  _detect_two_column returns False and
extract_pdf_text falls back to pdfplumber's default page.extract_text(),
which preserves natural top-to-bottom, left-to-right reading order.

Unambiguous ordering: THETA → IOTA → KAPPA (three successive body paragraphs).
"""

import struct
import zlib
from pathlib import Path

import pytest

from litexplorer.services.pdf import ExtractionError, _detect_two_column, extract_pdf_text

# ---------------------------------------------------------------------------
# Fixture paths
# ---------------------------------------------------------------------------

FIXTURES = Path(__file__).parent / "fixtures" / "pdfs"
TWO_COL = FIXTURES / "two_column.pdf"
SINGLE_COL = FIXTURES / "single_column.pdf"


# ---------------------------------------------------------------------------
# Helper: load words + page width from the first page
# ---------------------------------------------------------------------------

def _first_page_words_and_width(pdf_path: Path):
    import pdfplumber

    with pdfplumber.open(pdf_path) as pdf:
        page = pdf.pages[0]
        return page.extract_words(x_tolerance=1, y_tolerance=3), page.width


# ---------------------------------------------------------------------------
# two_column.pdf tests
# ---------------------------------------------------------------------------

class TestTwoColumnPdf:
    def test_two_column_detected(self):
        """_detect_two_column must return True for the two-column fixture."""
        words, width = _first_page_words_and_width(TWO_COL)
        assert _detect_two_column(words, width) is True

    def test_two_column_left_before_right(self):
        """Left-column sentinel 'LEFTCOL' must appear before 'RIGHTCOL'."""
        text = extract_pdf_text(TWO_COL)
        lc = text.find("LEFTCOL")
        rc = text.find("RIGHTCOL")
        assert lc != -1, "'LEFTCOL' not found"
        assert rc != -1, "'RIGHTCOL' not found"
        assert lc < rc, f"LEFTCOL (pos {lc}) must precede RIGHTCOL (pos {rc})"

    def test_two_column_title_present(self):
        """The title word 'Synthetic' must appear in the extracted text.

        'Synthetic Test Paper' straddles mid_x so the words land in different
        column groups.  We assert the left-half portion ('Synthetic') is present.
        """
        text = extract_pdf_text(TWO_COL)
        assert "Synthetic" in text

    def test_two_column_abstract_present(self):
        """The abstract sentinel 'ABSTRACT:' must appear in the extracted text."""
        text = extract_pdf_text(TWO_COL)
        assert "ABSTRACT:" in text

    def test_two_column_caption_present(self):
        """The caption prefix 'Figure 1' must appear in the extracted text."""
        text = extract_pdf_text(TWO_COL)
        assert "Figure 1" in text


# ---------------------------------------------------------------------------
# single_column.pdf tests
# ---------------------------------------------------------------------------

class TestSingleColumnPdf:
    def test_single_column_not_detected_as_two_col(self):
        """_detect_two_column must return False for the single-column fixture."""
        words, width = _first_page_words_and_width(SINGLE_COL)
        assert _detect_two_column(words, width) is False

    def test_single_column_singlecol_present_leftcol_absent(self):
        """'SINGLECOL' is present; 'LEFTCOL' must be absent (no false split)."""
        text = extract_pdf_text(SINGLE_COL)
        assert "SINGLECOL" in text
        assert "LEFTCOL" not in text

    def test_single_column_order(self):
        """Body keywords THETA, IOTA, KAPPA must appear in that order."""
        text = extract_pdf_text(SINGLE_COL)
        theta = text.find("THETA")
        iota = text.find("IOTA")
        kappa = text.find("KAPPA")
        assert theta != -1, "'THETA' not found"
        assert iota != -1, "'IOTA' not found"
        assert kappa != -1, "'KAPPA' not found"
        assert theta < iota < kappa, (
            f"Expected THETA ({theta}) < IOTA ({iota}) < KAPPA ({kappa})"
        )


# ---------------------------------------------------------------------------
# ExtractionError tests
# ---------------------------------------------------------------------------

class TestExtractionError:
    def test_no_text_layer_raises(self, tmp_path):
        """A PDF whose content is a graphics-only stream raises ExtractionError.

        The page content is 'q Q' (push/pop graphics state) — a no-op that
        produces no text operators, so pdfplumber extracts zero words.
        """
        content = b"q Q"

        # Build a minimal valid PDF by hand (no third-party lib needed)
        header = b"%PDF-1.4\n"
        obj1 = b"1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n"
        obj2 = b"2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n"
        obj3 = (
            b"3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792]"
            b" /Contents 4 0 R >>\nendobj\n"
        )
        obj4 = (
            b"4 0 obj\n<< /Length " + str(len(content)).encode() + b" >>\nstream\n"
            + content + b"\nendstream\nendobj\n"
        )
        objs = [obj1, obj2, obj3, obj4]
        pos = len(header)
        offsets: list[int] = []
        body = b""
        for obj in objs:
            offsets.append(pos)
            body += obj
            pos += len(obj)
        xref_pos = len(header) + len(body)
        xref = b"xref\n0 5\n0000000000 65535 f \n"
        for off in offsets:
            xref += f"{off:010d} 00000 n \n".encode()
        trailer = (
            b"trailer\n<< /Size 5 /Root 1 0 R >>\nstartxref\n"
            + str(xref_pos).encode()
            + b"\n%%EOF\n"
        )
        pdf_path = tmp_path / "no_text.pdf"
        pdf_path.write_bytes(header + body + xref + trailer)

        with pytest.raises(ExtractionError):
            extract_pdf_text(pdf_path)
